data:
  dataset_dir: '/data/lmalerba/lesions_patches_dataset'
  task: classification
  splits_file: '/data/lmalerba/lesions_patches_dataset/cv_splits_3.json'
  val_fold: 3
  transforms_name: moderate
  batch_size: 8
  num_workers: 0
  per_image_normalize: false # To be deactivated if global normalization was performed by lesion_patches_extraction.py

model:
  class: Deep3DCNN
  model_path: '/data/lmalerba/logs/Deep3DCNN_2/best_model.pt' 

loss:
  name: CrossEntropyLoss

logging:
  logdir: "/data/lmalerba/logs"

phase1:
  optim:
    algo: Adam
    params:
      lr: 0.001
  scheduler:
    algo: CosineAnnealingLR
    params:
      T_max: 15           # = nepochs for this phase
      eta_min: 0.00001